[package]
name = "shoehorn_cards"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

[dependencies]

mksvg = {path = "../../mlibs/mksvg/"}
lazy_conf = {path = "../../mlibs/lazy_conf/"}
